// _gen.cjs
// WBS 1.2.1 - Generates Firestore schema, rules, types and seed data.
// Run from inside the rhymix-react/ project folder.

'use strict';

const fs   = require('fs');
const path = require('path');

function write(filePath, lines) {
  const content = Array.isArray(lines) ? lines.join('\n') + '\n' : lines + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('  wrote:', filePath);
}

// ── firestore.rules ───────────────────────────────────────────
write('firestore.rules', [
  "rules_version = '2';",
  "service cloud.firestore {",
  "  match /databases/{database}/documents {",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // HELPER FUNCTIONS",
  "    // ════════════════════════════════════════════════════════",
  "",
  "    function isSignedIn() {",
  "      return request.auth != null;",
  "    }",
  "",
  "    function uid() {",
  "      return request.auth.uid;",
  "    }",
  "",
  "    function isOwner(resourceUid) {",
  "      return isSignedIn() && uid() == resourceUid;",
  "    }",
  "",
  "    function getMember() {",
  "      return get(/databases/$(database)/documents/members/$(request.auth.uid)).data;",
  "    }",
  "",
  "    function isAdmin() {",
  "      return isSignedIn() && getMember().isAdmin == true;",
  "    }",
  "",
  "    function isBanned() {",
  "      return isSignedIn() && getMember().status == 'banned';",
  "    }",
  "",
  "    function isActive() {",
  "      return isSignedIn() && !isBanned() && getMember().status == 'active';",
  "    }",
  "",
  "    function inGroup(groupId) {",
  "      return isSignedIn() && groupId in getMember().groupIds;",
  "    }",
  "",
  "    function getBoard(boardMid) {",
  "      return get(/databases/$(database)/documents/boards/$(boardMid)).data;",
  "    }",
  "",
  "    function canReadBoard(boardMid) {",
  "      let board = getBoard(boardMid);",
  "      return board.readGroupId == 'guest'",
  "             || (isSignedIn() && (board.readGroupId == 'member' || inGroup(board.readGroupId)));",
  "    }",
  "",
  "    function canWriteBoard(boardMid) {",
  "      let board = getBoard(boardMid);",
  "      return isActive() && (board.writeGroupId == 'member' || inGroup(board.writeGroupId));",
  "    }",
  "",
  "    function validString(field, minLen, maxLen) {",
  "      return field is string && field.size() >= minLen && field.size() <= maxLen;",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // MEMBERS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /members/{uid} {",
  "      // Anyone signed in can read basic profile",
  "      allow read: if isSignedIn();",
  "",
  "      // Create own member doc on registration",
  "      allow create: if isOwner(uid)",
  "                    && validString(request.resource.data.nickname, 2, 20)",
  "                    && request.resource.data.status == 'pending'",
  "                    && request.resource.data.isAdmin == false",
  "                    && request.resource.data.points == 0;",
  "",
  "      // Update own profile (cannot change isAdmin, status, points)",
  "      allow update: if (isOwner(uid)",
  "                    && !request.resource.data.diff(resource.data).affectedKeys()",
  "                       .hasAny(['isAdmin', 'status', 'points', 'groupIds']))",
  "                    || isAdmin();",
  "",
  "      // Only admin can delete members",
  "      allow delete: if isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // GROUPS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /groups/{groupId} {",
  "      allow read:  if isSignedIn();",
  "      allow write: if isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // BOARDS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /boards/{boardMid} {",
  "      allow read:  if true;   // board config is public",
  "      allow write: if isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // DOCUMENTS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /documents/{docSrl} {",
  "      allow read: if resource.data.status == 'public'",
  "                  && canReadBoard(resource.data.boardMid)",
  "                  || isOwner(resource.data.authorId)",
  "                  || isAdmin();",
  "",
  "      allow create: if canWriteBoard(request.resource.data.boardMid)",
  "                    && isOwner(request.resource.data.authorId)",
  "                    && validString(request.resource.data.title, 1, 255)",
  "                    && request.resource.data.status in ['public', 'secret']",
  "                    && request.resource.data.views == 0",
  "                    && request.resource.data.votes == 0;",
  "",
  "      allow update: if (isOwner(resource.data.authorId)",
  "                    && !request.resource.data.diff(resource.data)",
  "                       .affectedKeys().hasAny(['authorId', 'boardMid', 'views', 'votes']))",
  "                    || isAdmin();",
  "",
  "      allow delete: if isOwner(resource.data.authorId) || isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // COMMENTS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /comments/{commentSrl} {",
  "      allow read: if resource.data.isSecret == false",
  "                  || isOwner(resource.data.authorId)",
  "                  || isAdmin();",
  "",
  "      allow create: if isActive()",
  "                    && isOwner(request.resource.data.authorId)",
  "                    && validString(request.resource.data.content, 1, 5000)",
  "                    && request.resource.data.votes == 0;",
  "",
  "      allow update: if (isOwner(resource.data.authorId)",
  "                    && !request.resource.data.diff(resource.data)",
  "                       .affectedKeys().hasAny(['authorId', 'docSrl', 'votes']))",
  "                    || isAdmin();",
  "",
  "      allow delete: if isOwner(resource.data.authorId) || isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // NOTIFICATIONS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /notifications/{notifId} {",
  "      allow read:   if isOwner(resource.data.uid);",
  "      allow create: if isAdmin();   // only Cloud Functions create notifications",
  "      allow update: if isOwner(resource.data.uid)",
  "                    && request.resource.data.diff(resource.data)",
  "                       .affectedKeys().hasOnly(['read']);",
  "      allow delete: if isOwner(resource.data.uid) || isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // MENUS COLLECTION",
  "    // ════════════════════════════════════════════════════════",
  "    match /menus/{menuId} {",
  "      allow read:  if true;",
  "      allow write: if isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // SITE SETTINGS",
  "    // ════════════════════════════════════════════════════════",
  "    match /settings/{docId} {",
  "      allow read:  if true;",
  "      allow write: if isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // CATEGORIES (subcollection under boards)",
  "    // ════════════════════════════════════════════════════════",
  "    match /boards/{boardMid}/categories/{catId} {",
  "      allow read:  if true;",
  "      allow write: if isAdmin();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // VOTES (subcollection under documents)",
  "    // ════════════════════════════════════════════════════════",
  "    match /documents/{docSrl}/votes/{uid} {",
  "      allow read:  if isSignedIn();",
  "      allow write: if isOwner(uid) && isActive();",
  "    }",
  "",
  "    // ════════════════════════════════════════════════════════",
  "    // SCRAPS (subcollection under members)",
  "    // ════════════════════════════════════════════════════════",
  "    match /members/{uid}/scraps/{docSrl} {",
  "      allow read:   if isOwner(uid);",
  "      allow write:  if isOwner(uid) && isActive();",
  "    }",
  "",
  "    // Default deny",
  "    match /{document=**} {",
  "      allow read, write: if false;",
  "    }",
  "  }",
  "}",
]);

// ── firestore.indexes.json ────────────────────────────────────
write('firestore.indexes.json', JSON.stringify({
  indexes: [
    // Documents: list by board, newest first
    {
      collectionGroup: 'documents',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'boardMid',  order: 'ASCENDING'  },
        { fieldPath: 'status',    order: 'ASCENDING'  },
        { fieldPath: 'createdAt', order: 'DESCENDING' },
      ],
    },
    // Documents: list by board + category
    {
      collectionGroup: 'documents',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'boardMid',   order: 'ASCENDING'  },
        { fieldPath: 'categoryId', order: 'ASCENDING'  },
        { fieldPath: 'createdAt',  order: 'DESCENDING' },
      ],
    },
    // Documents: popular posts (by views)
    {
      collectionGroup: 'documents',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'boardMid', order: 'ASCENDING'  },
        { fieldPath: 'status',   order: 'ASCENDING'  },
        { fieldPath: 'views',    order: 'DESCENDING' },
      ],
    },
    // Documents: notices pinned to top
    {
      collectionGroup: 'documents',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'boardMid',  order: 'ASCENDING'  },
        { fieldPath: 'isNotice',  order: 'DESCENDING' },
        { fieldPath: 'createdAt', order: 'DESCENDING' },
      ],
    },
    // Comments: list by document, oldest first (threading)
    {
      collectionGroup: 'comments',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'docSrl',    order: 'ASCENDING' },
        { fieldPath: 'createdAt', order: 'ASCENDING' },
      ],
    },
    // Notifications: unread first per user
    {
      collectionGroup: 'notifications',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'uid',       order: 'ASCENDING'  },
        { fieldPath: 'read',      order: 'ASCENDING'  },
        { fieldPath: 'createdAt', order: 'DESCENDING' },
      ],
    },
    // Members: list by group
    {
      collectionGroup: 'members',
      queryScope: 'COLLECTION',
      fields: [
        { fieldPath: 'status',    order: 'ASCENDING'  },
        { fieldPath: 'createdAt', order: 'DESCENDING' },
      ],
    },
  ],
  fieldOverrides: [],
}, null, 2));

// ── src/types/firestore.ts ────────────────────────────────────
write('src/types/firestore.ts', [
  "import type { Timestamp } from 'firebase/firestore'",
  "",
  "// ── Member ───────────────────────────────────────────────────",
  "export interface MemberDoc {",
  "  uid:        string",
  "  email:      string",
  "  nickname:   string",
  "  avatarUrl?: string",
  "  bio?:       string",
  "  groupIds:   string[]",
  "  points:     number",
  "  status:     'active' | 'pending' | 'banned'",
  "  isAdmin:    boolean",
  "  extraFields: Record<string, string>",
  "  createdAt:  Timestamp",
  "  updatedAt:  Timestamp",
  "  lastLoginAt?: Timestamp",
  "}",
  "",
  "// ── Group ────────────────────────────────────────────────────",
  "export interface GroupDoc {",
  "  groupId:     string",
  "  name:        string",
  "  level:       number",
  "  permissions: {",
  "    canLogin:        boolean",
  "    canWrite:        boolean",
  "    canComment:      boolean",
  "    canUpload:       boolean",
  "    canDownload:     boolean",
  "    canDeleteOwn:    boolean",
  "    isManager:       boolean",
  "  }",
  "  createdAt: Timestamp",
  "}",
  "",
  "// ── Board ────────────────────────────────────────────────────",
  "export interface BoardDoc {",
  "  mid:           string           // URL slug e.g. 'free-board'",
  "  name:          string",
  "  description?:  string",
  "  layout:        'list' | 'gallery' | 'album' | 'webzine' | 'card'",
  "  readGroupId:   string           // 'guest' | 'member' | groupId",
  "  writeGroupId:  string           // 'member' | groupId",
  "  commentGroupId: string",
  "  uploadGroupId:  string",
  "  listCount:     number           // posts per page",
  "  allowVote:     boolean",
  "  allowSecret:   boolean",
  "  allowAttach:   boolean",
  "  sortOrder:     'latest' | 'popular' | 'comment'",
  "  isActive:      boolean",
  "  order:         number           // menu display order",
  "  createdAt:     Timestamp",
  "}",
  "",
  "// ── Category (subcollection: boards/{mid}/categories) ────────",
  "export interface CategoryDoc {",
  "  catId:    string",
  "  name:     string",
  "  order:    number",
  "  parentId?: string",
  "}",
  "",
  "// ── Document (Post) ──────────────────────────────────────────",
  "export interface DocumentDoc {",
  "  docSrl:      string",
  "  boardMid:    string",
  "  title:       string",
  "  content:     string             // HTML from rich-text editor",
  "  contentText: string             // Plain text for search indexing",
  "  authorId:    string",
  "  authorNick:  string             // Denormalised for list display",
  "  categoryId?: string",
  "  tags:        string[]",
  "  status:      'public' | 'secret' | 'trash'",
  "  isNotice:    boolean",
  "  isPinned:    boolean",
  "  views:       number",
  "  votes:       number",
  "  commentCount: number",
  "  attachments: AttachmentMeta[]",
  "  thumbnailUrl?: string",
  "  createdAt:   Timestamp",
  "  updatedAt:   Timestamp",
  "}",
  "",
  "export interface AttachmentMeta {",
  "  name:      string",
  "  storagePath: string",
  "  size:      number",
  "  mimeType:  string",
  "  downloads: number",
  "}",
  "",
  "// ── Comment ──────────────────────────────────────────────────",
  "export interface CommentDoc {",
  "  commentSrl:  string",
  "  docSrl:      string",
  "  boardMid:    string",
  "  authorId:    string",
  "  authorNick:  string",
  "  content:     string",
  "  parentId?:   string             // for threaded replies",
  "  isSecret:    boolean",
  "  isDeleted:   boolean",
  "  votes:       number",
  "  createdAt:   Timestamp",
  "  updatedAt:   Timestamp",
  "}",
  "",
  "// ── Notification ─────────────────────────────────────────────",
  "export interface NotificationDoc {",
  "  notifId:    string",
  "  uid:        string              // recipient",
  "  type:       'reply' | 'mention' | 'vote' | 'admin' | 'system'",
  "  title:      string",
  "  body:       string",
  "  refId?:     string              // docSrl or commentSrl",
  "  refUrl?:    string",
  "  read:       boolean",
  "  createdAt:  Timestamp",
  "}",
  "",
  "// ── Menu ─────────────────────────────────────────────────────",
  "export interface MenuDoc {",
  "  menuId:    string",
  "  items:     MenuItem[]",
  "  updatedAt: Timestamp",
  "}",
  "",
  "export interface MenuItem {",
  "  itemId:      string",
  "  label:       string",
  "  type:        'board' | 'url' | 'folder'",
  "  target:      '_self' | '_blank'",
  "  boardMid?:   string",
  "  url?:        string",
  "  icon?:       string",
  "  groupId?:    string             // hide from groups below this",
  "  order:       number",
  "  children:    MenuItem[]",
  "}",
  "",
  "// ── Site Settings ────────────────────────────────────────────",
  "export interface SiteSettingsDoc {",
  "  siteName:       string",
  "  siteUrl:        string",
  "  logoUrl?:       string",
  "  faviconUrl?:    string",
  "  description?:   string",
  "  timezone:       string",
  "  language:       string",
  "  maintenanceMode: boolean",
  "  updatedAt:      Timestamp",
  "}",
]);

// ── src/services/firestore.ts ─────────────────────────────────
write('src/services/firestore.ts', [
  "import {",
  "  collection,",
  "  doc,",
  "  CollectionReference,",
  "  DocumentReference,",
  "  query,",
  "  where,",
  "  orderBy,",
  "  limit,",
  "  startAfter,",
  "  getDocs,",
  "  getDoc,",
  "  type QueryDocumentSnapshot,",
  "  type DocumentData,",
  "} from 'firebase/firestore'",
  "import { db } from '@config/firebase'",
  "import type {",
  "  MemberDoc,",
  "  GroupDoc,",
  "  BoardDoc,",
  "  DocumentDoc,",
  "  CommentDoc,",
  "  NotificationDoc,",
  "  MenuDoc,",
  "  SiteSettingsDoc,",
  "} from '@types/firestore'",
  "",
  "// ── Typed collection references ───────────────────────────────",
  "function col<T>(path: string) {",
  "  return collection(db, path) as CollectionReference<T>",
  "}",
  "",
  "export const Collections = {",
  "  members:       col<MemberDoc>('members'),",
  "  groups:        col<GroupDoc>('groups'),",
  "  boards:        col<BoardDoc>('boards'),",
  "  documents:     col<DocumentDoc>('documents'),",
  "  comments:      col<CommentDoc>('comments'),",
  "  notifications: col<NotificationDoc>('notifications'),",
  "  menus:         col<MenuDoc>('menus'),",
  "  settings:      col<SiteSettingsDoc>('settings'),",
  "} as const",
  "",
  "// ── Typed document references ─────────────────────────────────",
  "export const Refs = {",
  "  member:   (uid: string)       => doc(Collections.members,       uid) as DocumentReference<MemberDoc>,",
  "  group:    (groupId: string)   => doc(Collections.groups,        groupId) as DocumentReference<GroupDoc>,",
  "  board:    (mid: string)       => doc(Collections.boards,        mid) as DocumentReference<BoardDoc>,",
  "  document: (docSrl: string)    => doc(Collections.documents,     docSrl) as DocumentReference<DocumentDoc>,",
  "  comment:  (commentSrl: string)=> doc(Collections.comments,      commentSrl) as DocumentReference<CommentDoc>,",
  "  settings: ()                  => doc(db, 'settings', 'site') as DocumentReference<SiteSettingsDoc>,",
  "  categories: (mid: string)     => collection(db, 'boards', mid, 'categories'),",
  "  votes:    (docSrl: string)    => collection(db, 'documents', docSrl, 'votes'),",
  "  scraps:   (uid: string)       => collection(db, 'members', uid, 'scraps'),",
  "} as const",
  "",
  "// ── Pagination helper ─────────────────────────────────────────",
  "export interface Page<T> {",
  "  items:   T[]",
  "  lastDoc: QueryDocumentSnapshot<DocumentData> | null",
  "  hasMore: boolean",
  "}",
  "",
  "export async function getDocumentPage(",
  "  boardMid: string,",
  "  pageSize = 20,",
  "  cursor?: QueryDocumentSnapshot<DocumentData>,",
  "): Promise<Page<DocumentDoc>> {",
  "  let q = query(",
  "    Collections.documents,",
  "    where('boardMid', '==', boardMid),",
  "    where('status',   '==', 'public'),",
  "    orderBy('isNotice', 'desc'),",
  "    orderBy('createdAt', 'desc'),",
  "    limit(pageSize + 1),",
  "  )",
  "  if (cursor) q = query(q, startAfter(cursor))",
  "",
  "  const snap  = await getDocs(q)",
  "  const items = snap.docs.slice(0, pageSize).map((d) => d.data())",
  "  return {",
  "    items,",
  "    lastDoc: snap.docs[pageSize - 1] ?? null,",
  "    hasMore: snap.docs.length > pageSize,",
  "  }",
  "}",
  "",
  "export async function getBoard(mid: string): Promise<BoardDoc | null> {",
  "  const snap = await getDoc(Refs.board(mid))",
  "  return snap.exists() ? snap.data() : null",
  "}",
  "",
  "export async function getDocument(docSrl: string): Promise<DocumentDoc | null> {",
  "  const snap = await getDoc(Refs.document(docSrl))",
  "  return snap.exists() ? snap.data() : null",
  "}",
  "",
  "export async function getMember(uid: string): Promise<MemberDoc | null> {",
  "  const snap = await getDoc(Refs.member(uid))",
  "  return snap.exists() ? snap.data() : null",
  "}",
]);

// ── firestore-seed/seed.cjs ───────────────────────────────────
write('firestore-seed/seed.cjs', [
  "#!/usr/bin/env node",
  "// Seed script – populates Firestore with sample data for development.",
  "// Run: GOOGLE_APPLICATION_CREDENTIALS=./service-account.json node firestore-seed/seed.cjs",
  "// Or against emulator: FIRESTORE_EMULATOR_HOST=localhost:8080 node firestore-seed/seed.cjs",
  "",
  "'use strict';",
  "",
  "const { initializeApp, cert, getApps } = require('firebase-admin/app');",
  "const { getFirestore, Timestamp }       = require('firebase-admin/firestore');",
  "",
  "if (!getApps().length) {",
  "  if (process.env.FIRESTORE_EMULATOR_HOST) {",
  "    initializeApp({ projectId: 'rhymix-react-dev' });",
  "  } else {",
  "    initializeApp({ credential: cert(require('../service-account.json')) });",
  "  }",
  "}",
  "",
  "const db  = getFirestore();",
  "const now = Timestamp.now();",
  "",
  "async function seed() {",
  "  console.log('Seeding Firestore...');",
  "",
  "  // ── Site settings ────────────────────────────────────────",
  "  await db.doc('settings/site').set({",
  "    siteName:        'Rhymix React',",
  "    siteUrl:         'http://localhost:3000',",
  "    description:     'A modern CMS built with React and Firebase',",
  "    timezone:        'Asia/Seoul',",
  "    language:        'ko',",
  "    maintenanceMode: false,",
  "    updatedAt:       now,",
  "  });",
  "  console.log('  created: settings/site');",
  "",
  "  // ── Default groups ───────────────────────────────────────",
  "  const groups = [",
  "    { groupId: 'admin',   name: '관리자', level: 10, permissions: { canLogin: true,  canWrite: true,  canComment: true,  canUpload: true,  canDownload: true,  canDeleteOwn: true,  isManager: true  } },",
  "    { groupId: 'manager', name: '매니저', level: 5,  permissions: { canLogin: true,  canWrite: true,  canComment: true,  canUpload: true,  canDownload: true,  canDeleteOwn: true,  isManager: true  } },",
  "    { groupId: 'member',  name: '회원',   level: 2,  permissions: { canLogin: true,  canWrite: true,  canComment: true,  canUpload: true,  canDownload: true,  canDeleteOwn: true,  isManager: false } },",
  "    { groupId: 'guest',   name: '손님',   level: 1,  permissions: { canLogin: false, canWrite: false, canComment: false, canUpload: false, canDownload: false, canDeleteOwn: false, isManager: false } },",
  "  ];",
  "  for (const g of groups) {",
  "    await db.doc('groups/' + g.groupId).set({ ...g, createdAt: now });",
  "    console.log('  created: groups/' + g.groupId);",
  "  }",
  "",
  "  // ── Sample boards ────────────────────────────────────────",
  "  const boards = [",
  "    { mid: 'notice',    name: '공지사항', layout: 'list',    readGroupId: 'guest',  writeGroupId: 'admin',  commentGroupId: 'member', uploadGroupId: 'admin',  listCount: 20, allowVote: false, allowSecret: false, allowAttach: true,  sortOrder: 'latest', isActive: true, order: 1 },",
  "    { mid: 'free',      name: '자유게시판', layout: 'list',  readGroupId: 'guest',  writeGroupId: 'member', commentGroupId: 'member', uploadGroupId: 'member', listCount: 20, allowVote: true,  allowSecret: true,  allowAttach: true,  sortOrder: 'latest', isActive: true, order: 2 },",
  "    { mid: 'gallery',   name: '갤러리',   layout: 'gallery', readGroupId: 'guest',  writeGroupId: 'member', commentGroupId: 'member', uploadGroupId: 'member', listCount: 24, allowVote: true,  allowSecret: false, allowAttach: true,  sortOrder: 'latest', isActive: true, order: 3 },",
  "    { mid: 'qna',       name: 'Q&A',      layout: 'list',    readGroupId: 'member', writeGroupId: 'member', commentGroupId: 'member', uploadGroupId: 'member', listCount: 20, allowVote: true,  allowSecret: true,  allowAttach: true,  sortOrder: 'latest', isActive: true, order: 4 },",
  "  ];",
  "  for (const b of boards) {",
  "    await db.doc('boards/' + b.mid).set({ ...b, createdAt: now });",
  "    console.log('  created: boards/' + b.mid);",
  "  }",
  "",
  "  // ── Default menu ─────────────────────────────────────────",
  "  await db.doc('menus/main').set({",
  "    menuId: 'main',",
  "    items: [",
  "      { itemId: '1', label: '공지사항', type: 'board', boardMid: 'notice',  target: '_self', order: 1, children: [] },",
  "      { itemId: '2', label: '자유게시판', type: 'board', boardMid: 'free',  target: '_self', order: 2, children: [] },",
  "      { itemId: '3', label: '갤러리',   type: 'board', boardMid: 'gallery', target: '_self', order: 3, children: [] },",
  "      { itemId: '4', label: 'Q&A',      type: 'board', boardMid: 'qna',     target: '_self', order: 4, children: [] },",
  "    ],",
  "    updatedAt: now,",
  "  });",
  "  console.log('  created: menus/main');",
  "",
  "  console.log('');",
  "  console.log('Seed complete.');",
  "}",
  "",
  "seed().catch((err) => { console.error(err); process.exit(1); });",
]);

console.log('');
console.log('All Firestore schema files generated successfully.');
