// _gen.cjs
// WBS 1.1.3 - Generates GitHub Actions workflow files.
// Run from inside the rhymix-react/ project folder.

'use strict';

const fs   = require('fs');
const path = require('path');

function write(filePath, lines) {
  const content = Array.isArray(lines) ? lines.join('\n') + '\n' : lines;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('  wrote:', filePath);
}

// ── .github/workflows/ci.yml ──────────────────────────────────
write('.github/workflows/ci.yml', [
  "name: CI",
  "",
  "on:",
  "  push:",
  "    branches: [main, develop]",
  "  pull_request:",
  "    branches: [main, develop]",
  "",
  "concurrency:",
  "  group: ci-${{ github.ref }}",
  "  cancel-in-progress: true",
  "",
  "jobs:",
  "  lint:",
  "    name: Lint",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "",
  "      - name: Setup Node",
  "        uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 20",
  "          cache: npm",
  "",
  "      - name: Install dependencies",
  "        run: npm ci",
  "",
  "      - name: Run ESLint",
  "        run: npm run lint",
  "",
  "      - name: Check Prettier formatting",
  "        run: npm run format:check",
  "",
  "      - name: TypeScript type check",
  "        run: npm run type-check",
  "",
  "  test:",
  "    name: Test",
  "    runs-on: ubuntu-latest",
  "    needs: lint",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "",
  "      - name: Setup Node",
  "        uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 20",
  "          cache: npm",
  "",
  "      - name: Install dependencies",
  "        run: npm ci",
  "",
  "      - name: Run tests with coverage",
  "        run: npm run test:cov",
  "",
  "      - name: Upload coverage report",
  "        uses: actions/upload-artifact@v4",
  "        with:",
  "          name: coverage",
  "          path: coverage/",
  "          retention-days: 7",
  "",
  "  build:",
  "    name: Build",
  "    runs-on: ubuntu-latest",
  "    needs: test",
  "    env:",
  "      VITE_FIREBASE_API_KEY:              ${{ secrets.VITE_FIREBASE_API_KEY }}",
  "      VITE_FIREBASE_AUTH_DOMAIN:          ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}",
  "      VITE_FIREBASE_PROJECT_ID:           ${{ secrets.VITE_FIREBASE_PROJECT_ID }}",
  "      VITE_FIREBASE_STORAGE_BUCKET:       ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}",
  "      VITE_FIREBASE_MESSAGING_SENDER_ID:  ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}",
  "      VITE_FIREBASE_APP_ID:               ${{ secrets.VITE_FIREBASE_APP_ID }}",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "",
  "      - name: Setup Node",
  "        uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 20",
  "          cache: npm",
  "",
  "      - name: Install dependencies",
  "        run: npm ci",
  "",
  "      - name: Build",
  "        run: npm run build",
  "",
  "      - name: Upload build artifact",
  "        uses: actions/upload-artifact@v4",
  "        with:",
  "          name: dist",
  "          path: dist/",
  "          retention-days: 1",
]);

// ── .github/workflows/deploy.yml ─────────────────────────────
write('.github/workflows/deploy.yml', [
  "name: Deploy to Firebase",
  "",
  "on:",
  "  push:",
  "    branches: [main]",
  "  release:",
  "    types: [published]",
  "",
  "jobs:",
  "  deploy:",
  "    name: Deploy",
  "    runs-on: ubuntu-latest",
  "    environment:",
  "      name: ${{ github.event_name == 'release' && 'production' || 'staging' }}",
  "      url: ${{ github.event_name == 'release' && 'https://your-project.web.app' || 'https://your-project--staging.web.app' }}",
  "    env:",
  "      VITE_FIREBASE_API_KEY:              ${{ secrets.VITE_FIREBASE_API_KEY }}",
  "      VITE_FIREBASE_AUTH_DOMAIN:          ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}",
  "      VITE_FIREBASE_PROJECT_ID:           ${{ secrets.VITE_FIREBASE_PROJECT_ID }}",
  "      VITE_FIREBASE_STORAGE_BUCKET:       ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}",
  "      VITE_FIREBASE_MESSAGING_SENDER_ID:  ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}",
  "      VITE_FIREBASE_APP_ID:               ${{ secrets.VITE_FIREBASE_APP_ID }}",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "",
  "      - name: Setup Node",
  "        uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 20",
  "          cache: npm",
  "",
  "      - name: Install dependencies",
  "        run: npm ci",
  "",
  "      - name: Build",
  "        run: npm run build",
  "",
  "      - name: Deploy to Firebase Hosting (staging)",
  "        if: github.event_name == 'push' && github.ref == 'refs/heads/main'",
  "        uses: FirebaseExtended/action-hosting-deploy@v0",
  "        with:",
  "          repoToken: ${{ secrets.GITHUB_TOKEN }}",
  "          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}",
  "          projectId: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}",
  "          channelId: staging",
  "",
  "      - name: Deploy to Firebase Hosting (production)",
  "        if: github.event_name == 'release'",
  "        uses: FirebaseExtended/action-hosting-deploy@v0",
  "        with:",
  "          repoToken: ${{ secrets.GITHUB_TOKEN }}",
  "          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}",
  "          projectId: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}",
  "          channelId: live",
]);

// ── .github/pull_request_template.md ─────────────────────────
write('.github/pull_request_template.md', [
  "## Summary",
  "<!-- What does this PR do? Reference the WBS task number. -->",
  "",
  "## Type of change",
  "- [ ] New feature (WBS task: ___)",
  "- [ ] Bug fix",
  "- [ ] Refactor",
  "- [ ] Chore / config",
  "",
  "## Checklist",
  "- [ ] `npm run lint` passes with no errors",
  "- [ ] `npm run type-check` passes",
  "- [ ] `npm test` passes",
  "- [ ] New code has tests where applicable",
  "- [ ] No console.log left in production code",
  "- [ ] Firestore security rules updated if schema changed",
  "",
  "## Screenshots (if UI change)",
  "<!-- Paste before/after screenshots here -->",
]);

// ── .env.example ─────────────────────────────────────────────
write('.env.example', [
  "# Copy this file to .env.local and fill in your Firebase values.",
  "# NEVER commit .env.local to git.",
  "",
  "VITE_FIREBASE_API_KEY=",
  "VITE_FIREBASE_AUTH_DOMAIN=",
  "VITE_FIREBASE_PROJECT_ID=",
  "VITE_FIREBASE_STORAGE_BUCKET=",
  "VITE_FIREBASE_MESSAGING_SENDER_ID=",
  "VITE_FIREBASE_APP_ID=",
  "VITE_FIREBASE_MEASUREMENT_ID=",
]);

console.log('');
console.log('All workflow files generated successfully.');
